version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: thj-postgres-db-container
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: the-hunters-journal
    ports:
      - "5432:5432"
  